# ./YoLo_Det/config_det/train_param/train_det.yaml
model:
  pretrained: ./YoLo_BB/backborn_model/yolo11s.pt   # 검출 전용 가중치(.pt)

# --- Data ---
# 14일 이전에 모은 약 300개 데이터 사용
data:
  yaml: "./datasets/Bounding_Box/Train_1017/data.yaml"

# --- Training ---
train:
  project: ./YoLo_BB/train_results
  name: train_bb
  epochs: 300
  imgsz: 640
  batch: 8
  workers: 2
  device: 0                    # GPU 0, 또는 'cpu'
  optimizer: auto
  lr0: 0.01
  lrf: 0.01
  
  # augmentation
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 0.0

  # early stop
  patience: 30

